server:
  servlet:
    context-path: /fan
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/emp?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 20001023
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
