server:
  servlet:
    context-path: /fan
spring:
#静态资源
  web:
    resources:
      static-locations: classpath:templates/,classpath:static/
  #thymeleaf组件
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true


  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://192.168.186.85:3306/fuantuanfood?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 20001023
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
#  web:
#    resources:
#      static-locations: classpath:static/*
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
  type-aliases-package: com.entity
  mapper-locations: classpath:com/chixing/mapper/*.xml
